// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAM_XFBHfASyfmtwlcZJSfRihKS-xzg7sg',
    appId: '1:647516722162:web:d5ac87f46b333bdfbb516b',
    messagingSenderId: '647516722162',
    projectId: 'fir-flutter-codelab-aef6c',
    authDomain: 'fir-flutter-codelab-aef6c.firebaseapp.com',
    storageBucket: 'fir-flutter-codelab-aef6c.appspot.com',
    measurementId: 'G-78WY354PKD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlk-oRi03WwTi5BrS5qOv4IEAm8uSGZ8M',
    appId: '1:647516722162:android:420085f7e40f254dbb516b',
    messagingSenderId: '647516722162',
    projectId: 'fir-flutter-codelab-aef6c',
    storageBucket: 'fir-flutter-codelab-aef6c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCnuD6hv3Uf0cE8wffwHN4OPjYmD-qPgw',
    appId: '1:647516722162:ios:af183c42cc092155bb516b',
    messagingSenderId: '647516722162',
    projectId: 'fir-flutter-codelab-aef6c',
    storageBucket: 'fir-flutter-codelab-aef6c.appspot.com',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCnuD6hv3Uf0cE8wffwHN4OPjYmD-qPgw',
    appId: '1:647516722162:ios:af183c42cc092155bb516b',
    messagingSenderId: '647516722162',
    projectId: 'fir-flutter-codelab-aef6c',
    storageBucket: 'fir-flutter-codelab-aef6c.appspot.com',
    iosBundleId: 'com.example.gtkFlutter',
  );

}